name: cloudcostlens
version: "1.0.0"
config-version: 2

profile: cloudcostlens

model-paths: ["models"]

models:
  cloudcostlens:
    staging:
      +materialized: view
    marts:
      +materialized: table